[MEMORY]
VECTORS = { start = "$0000", size = "$100", type = "ro", fill = "$00" }
GBC_HEADER = { start = "$0100", size = "$50", type = "ro", fill = "$00" }
ROM00 = { start = "$0150", size = "$3EB0", type = "ro", fill = "$00" }
ROM01 = { start = "$4000", size = "$4000", type = "ro", fill = "$00" }
ROM02 = { start = "$4000", size = "$4000", type = "ro", fill = "$00" }
ROM03 = { start = "$4000", size = "$4000", type = "ro", fill = "$00" }
ROM04 = { start = "$4000", size = "$4000", type = "ro", fill = "$00" }
ROM05 = { start = "$4000", size = "$4000", type = "ro", fill = "$00" }
ROM06 = { start = "$4000", size = "$4000", type = "ro", fill = "$00" }
ROM07 = { start = "$4000", size = "$4000", type = "ro", fill = "$00" }

HRAM = { start = "$FF80", size = "$7E", type = "rw" }

[SECTIONS]
VECTORS = { load = "VECTORS", type = "ro" }
GBC_HEADER = { load = "GBC_HEADER", type = "ro" }
HOME = { load = "ROM00", type = "ro", tags = { bank = "$00" } }
ROM01 = { load = "ROM01", type = "ro", tags = { bank = "$01" } }
HRAM = { load = "HRAM", type = "bss" }
